version: "3.9"

services:
  db:
    image: postgres
    container_name: dtd_postgres
    # Not persisting data intentionally.
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine
    container_name: dtd_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6380:6380"
    command: redis-server --port 6380

  source:
    build: .
    container_name: dtd_source
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        apt update
        apt install findutils
        find source -path "*/migrations/*.py" -not -name "__init__.py" -delete
        find source -path "*/migrations/*.pyc"  -delete
        find source -path "*/db.sqlite3" -delete
        python source/manage.py makemigrations
        python source/manage.py migrate
        cd source && python -m app.scripts.script && cd ..
        python source/manage.py runserver 0.0.0.0:4000

    volumes:
      - ./source:/code/source
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - db

  target:
    build: .
    container_name: dtd_target
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        python target/manage.py runserver 0.0.0.0:5000

    volumes:
      - ./target:/code/target
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db
      - source

  test:
    build: .
    container_name: dtd_test
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        pip install -r requirements-dev.txt
        black . --check
        isort . --check
        pytest tests/integration_tests.py -s -v

    volumes:
      - ./:/code/
    ports:
      - "6000:6000"
    depends_on:
      - redis
      - db
      - source
      - target
