version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: dtd_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6380:6380"
    command: redis-server --port 6380

  source:
    build: .
    container_name: dtd_source
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        apt update
        apt install findutils
        find source -path "*/migrations/*.py" -not -name "__init__.py" -delete
        find source -path "*/migrations/*.pyc"  -delete
        find source -path "*/db.sqlite3" -delete
        python source/manage.py makemigrations
        python source/manage.py migrate
        cd source && python -m app.scripts.script && cd ..
        python source/manage.py runserver 0.0.0.0:4000

    volumes:
      - ./source:/code/source
    ports:
      - "4000:4000"
    depends_on:
      - redis

  target:
    build: .
    container_name: dtd_target
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        apt update
        apt install findutils
        find target -path "*/migrations/*.py" -not -name "__init__.py" -delete
        find target -path "*/migrations/*.pyc"  -delete
        find target -path "*/db.sqlite3" -delete
        python target/manage.py runserver 0.0.0.0:5000

    volumes:
      - ./target:/code/target
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - source
