name: Django Template Delocalization Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the Dependencies
        run: |
          echo "Upgrading pip ...."
          python -m pip install --upgrade pip
          echo 'requirements.txt requirements-dev.txt' | \
          xargs -n 1 -P 2 python -m pip install -r

      - name: Check Linter
        run: |
          echo "Checking linter formatting..."
          python -m pip black --check .
          python -m pip isort --check .

      - name: Spin Up the Containers
        run: |
          make start_servers
          python -m pytest tests/integration_tests.py
